export const Courses = [
    {
        category
            :
            "648404f02c0a3dd73ea0144c",
        desc
            :
            "This is CCC Course",
        duration
            :
            "20",
        img
            :
            "1690717858063drew-beamer-Vc1pJfvoQvY-unsplash.jpg",
        instructor
            :
            "64b756ab7dd2aec761f9ea9f",
        lessons
            :
            20,
        level
            :
            "Beginner",
        price
            :
            5000,
        rating
            :
            2,
        status
            :
            "active",
        title
            :
            "CCNA",
        __v
            :
            0,
        _id
            :
            "64b754cc7dd2aec761f9ea63",
    },
    {
        category
            :
            "648404f02c0a3dd73ea0144c",
        desc
            :
            "This is CCC Course",
        duration
            :
            "20",
        img
            :
            "1690717858063drew-beamer-Vc1pJfvoQvY-unsplash.jpg",
        instructor
            :
            "64b756ab7dd2aec761f9ea9f",
        lessons
            :
            20,
        level
            :
            "Beginner",
        price
            :
            5000,
        rating
            :
            2,
        status
            :
            "active",
        title
            :
            "CCC",
        __v
            :
            1,
        _id
            :
            "64b754cc7dd2aec761f9ea63",
    },
    {
        category
            :
            "648404f02c0a3dd73ea0144c",
        desc
            :
            "This is CCC Course",
        duration
            :
            "20",
        img
            :
            "1690717858063drew-beamer-Vc1pJfvoQvY-unsplash.jpg",
        instructor
            :
            "64b756ab7dd2aec761f9ea9f",
        lessons
            :
            20,
        level
            :
            "Beginner",
        price
            :
            5000,
        rating
            :
            2,
        status
            :
            "active",
        title
            :
            "ADCA",
        __v
            :
            2,
        _id
            :
            "64b754cc7dd2aec761f9ea63",
    },
    {
        category
            :
            "648404f02c0a3dd73ea0144c",
        desc
            :
            "This is CCC Course",
        duration
            :
            "20",
        img
            :
            "1690717858063drew-beamer-Vc1pJfvoQvY-unsplash.jpg",
        instructor
            :
            "64b756ab7dd2aec761f9ea9f",
        lessons
            :
            20,
        level
            :
            "Beginner",
        price
            :
            5000,
        rating
            :
            2,
        status
            :
            "active",
        title
            :
            "DCA",
        __v
            :
            3,
        _id
            :
            "64b754cc7dd2aec761f9ea63",
    },
    {
        category
            :
            "648404f02c0a3dd73ea0144c",
        desc
            :
            "This is CCC Course",
        duration
            :
            "20",
        img
            :
            "1690717858063drew-beamer-Vc1pJfvoQvY-unsplash.jpg",
        instructor
            :
            "64b756ab7dd2aec761f9ea9f",
        lessons
            :
            20,
        level
            :
            "Beginner",
        price
            :
            5000,
        rating
            :
            2,
        status
            :
            "active",
        title
            :
            "DCA",
        __v
            :
            4,
        _id
            :
            "64b754cc7dd2aec761f9ea63",
    }
]